### ISSUE TITLE
After installing the extension, trying the help/quick phrases does nothing

### ISSUE THREAD

**Issue by bojomojo** [kbysiec/vscode-search-everywhere#4] opened 2020-09-02 12:43 UTC
For example I set the help phrase as ??
when I type ?? nothing happens..

same for @@/##/$$ it just says no symbols found, without even writing a symbol to search for.

Am I missing anything? how do I trigger the search

**Comment by kbysiec** [comment] 2020-09-02 13:01
Hi! Thanks for the issue.

It shouldn't be necessary but have you tried to relaunch vsc? Before changing the help phrase everything was working without any problems?

If you could provide some gif or print screen it would be great.

**Comment by bojomojo** [comment] 2020-09-02 13:05
I did try to relaunch it multiple times.

![image](https://user-images.githubusercontent.com/62281574/91986878-92c64500-ed2d-11ea-8d11-6fafcad5d09a.png)

![image](https://user-images.githubusercontent.com/62281574/91986949-a8d40580-ed2d-11ea-99d7-d52264ad91b2.png)

**Comment by kbysiec** [comment] 2020-09-02 13:09
Please try to invoke Reload from command palette. The whole project should be reindexed. I assume you have at least one project opened, right?

**Comment by bojomojo** [comment] 2020-09-02 13:11
did searcheverywhere.reload, and it was autocompleting the command. But nothing happened at all once I did

**Comment by kbysiec** [comment] 2020-09-02 13:45
Ok, thanks for confirmation. In what language it is written? Is it open source? If yes please provide me with the link.

There is a setting named 'include' where by default ts and J's extensions are allowed. Maybe it causes zero results.

**Comment by bojomojo** [comment] 2020-09-02 14:49
its not open source unfortuantely.
I already modified the inclue to include all c/cpp files.

I will wait till vscode parsing is complete and try again

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-02 15:06
Hope it helps. Please let me know if it's working or we need to investigate it further.

Thanks for using the extension!

**Comment by bojomojo** [comment] 2020-09-03 07:03
still same problem exists..its as if the extension is disabled or something.

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-03 08:04
could you provide your extension settings?

In the meantime I will try to open any cpp project to verify it.

**Comment by bojomojo** [comment] 2020-09-03 09:13
"searchEverywhere.include": [
"**/*.{js,jsx,ts,tsx}",
"**/*.{c,h,cpp,inc,unt,json}"
],
"searchEverywhere.shouldHighlightSymbol": true,
"searchEverywhere.shouldDisplayNotificationInStatusBar": true,
"searchEverywhere.shouldUseFilesAndSearchExclude": true,
"searchEverywhere.helpPhrase": "??",
"searchEverywhere.itemsFilterPhrases": {
"0": "$$",
"4": "@@",
"11": "!!",
"14": "##",
"17": "%%"
},
"searchEverywhere.shouldInitOnStartup": true,
"searchEverywhere.icons": {

"0": "file-code",
"1": "file-submodule",
"2": "archive",
"3": "package",
"4": "checklist",
"5": "list-unordered",
"6": "tag",
"7": "location",
"8": "plus-circle",
"9": "list-ordered",
"10": "milestone",
"11": "zap",
"12": "beaker",
"13": "shield-lock",
"14": "note",
"15": "file-binary",
"16": "mirror",
"17": "server",
"18": "code",
"19": "key",
"20": "dot",
"21": "kebab-horizontal",
"22": "filter",
"23": "fire",
"24": "cpu",
"25": "north-star"
}

Sent from my iPad

On 3. Sep 2020, at 10:05, Kamil Bysiec <notifications@github.com> wrote:

﻿

could you provide your extension settings?

In the meantime I will try to open any cpp project to verify it.

**Comment by kbysiec** [comment] 2020-09-03 10:21
Thank you for your settings. I think you found a bug related to "include" setting. Could you replace this:

```
"searchEverywhere.include": [
"**/*.{js,jsx,ts,tsx}",
"**/*.{c,h,cpp,inc,unt,json}"
],

```
with

```
"searchEverywhere.include": [
"**/*.{c,h,cpp,inc,unt,json,js,jsx,ts,tsx}"
],
```

I think the problem is with multiline "include" setting. In the meantime I have cloned the hello world in cpp and successfully opened and indexed the project without any problems but my settings were only in one line.

![Screenshot 2020-09-03 at 10 23 31](https://user-images.githubusercontent.com/26285420/92102927-8b5f7400-eddf-11ea-9824-a0638f399844.png)

![ezgif com-optimize](https://user-images.githubusercontent.com/26285420/92103216-ebeeb100-eddf-11ea-8f8f-9619f9cf5334.gif)

**Comment by bojomojo** [comment] 2020-09-03 10:35
Done, but I am still seeing the same problem.. even when I invoke searcheverywhere.reload, nothing happens

**Comment by kbysiec** [comment] 2020-09-08 10:56
Does the problem still persist and you need an assistance or I can close the issue?

**Comment by bojomojo** [comment] 2020-09-09 07:42
no, still not working.
I am now getting down at the bottom right an error from the extension:

[cid:789f6744-098c-4c24-8eb2-c7d3ca67899f]

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-09 08:01
Thanks for information. Could you provide the screenshot?

**Comment by bojomojo** [comment] 2020-09-09 08:44
<img width="455" alt="DA8EF5C1-FD88-4F94-A385-70644F45A3AA" src="https://user-images.githubusercontent.com/62281574/92576120-6c525d80-f289-11ea-85e7-d0e376dd76ff.png">

**Comment by kbysiec** [comment] 2020-09-09 11:14
Thank you for the print screen. The following error is caused due to the fact I have published new version few days ago which changed the type of searchEverywhere.include setting type (from array to string). To fix it, please go to your settings in json format and change:

```
"searchEverywhere.include": [
"**/*.{c,h,cpp,inc,unt,json,js,jsx,ts,tsx}"
],
```

to the following:

`"searchEverywhere.include": "**/*.{c,h,cpp,inc,unt,json,js,jsx,ts,tsx}",`

Please let me know how it looks after that.

**Comment by bojomojo** [comment] 2020-09-09 11:22
the error is gone.. but nothing happens.
Reload does nothing
Search does nothing (even via the shortcut).

Also trying "??" does nothing. After the first ? the normal vscode help commands appear. Then with the second ?? everything disappears

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-09 11:25
Have you tried to open another project e.g. in different language? Or to limit the possible search results to only one file extension e.g. json? It would be good to establish which file extension is problematic.

**Comment by bojomojo** [comment] 2020-09-09 11:26
I think the fact that "??" or "Reload" do not work, means it has nothing to do with file extensions. I could try with a new workspace

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-09 11:32
Nope, without going into details the extension works in the following way:

1. Get all files from workspace based on include setting
2. For each file get all it's symbols
3. Limit the results according to exclude and itemsFilter settings,
4. If shouldUseItemsFilterPhrases setting is true, add the helpPhrase listener to display the list. If it is disabled, it doesn't react to it.

**Comment by bojomojo** [comment] 2020-09-09 11:47
reset the extensions to default and created a new much smaller workspace.

now going into the command pallette CMD+3 and then typing ?? doesnt work
but doing search Option+CMD+P and then ?? does work.

however both do not work on my large workspace.

I am on MAC OS, maybe that has any difference

Best Regards,
Shadi


________________________________

**Comment by kbysiec** [comment] 2020-09-09 12:17
Ok, but as I understand you were able to launch the quick pick with some indexed items, right? Was it in js/ts as the default is set up or it was c/cpp like the previous one?

Regarding the Option+Cmd+P - it is the default shortcut assigned for MacOS. I am working on Mac as well so it should not be the case.

I do not know anything regarding Cmd+3 - I assume it is your custom shortcut - maybe resetting the extension you reset the shortcut as well?

For your large workspace in c/cpp can you try the following settings to test if it helps somehow?

```
"searchEverywhere.helpPhrase": "??",
  "searchEverywhere.include": "**/*.{cpp}",
  "searchEverywhere.itemsFilter": {
    "allowedKinds": [0],
    "ignoredKinds": [],
    "ignoredNames": []
  }
```
Using the above you should have indexed only files (without symbols related to them) for cpp extension only. The helpPhrase is the same as you set it up "??".

Could you test and share the results?
Thanks.

**Comment by bojomojo** [comment] 2020-09-09 15:52
I reset the settings and set again to c files, and now its indexing. But its taking too long.
Does it need any internet connection during indexing?

Sent from my iPhone

On 9. Sep 2020, at 14:17, Kamil Bysiec <notifications@github.com> wrote:

﻿

Ok, but as I understand you were able to launch the quick pick with some indexed items, right? Was it in js/ts as the default is set up or it was c/cpp like the previous one?

Regarding the Option+Cmd+P - it is the default shortcut assigned for MacOS. I am working on Mac as well so it should not be the case.

I do not know anything regarding Cmd+3 - I assume it is your custom shortcut - maybe resetting the extension you reset the shortcut as well?

For your large workspace in c/cpp can you try the following settings to test if it helps somehow?

"searchEverywhere.helpPhrase": "??",
  "searchEverywhere.include": "**/*.{cpp}",
  "searchEverywhere.itemsFilter": {
    "allowedKinds": [0],
    "ignoredKinds": [],
    "ignoredNames": []
  }


Using the above you should have indexed only files (without symbols related to them) for cpp extension only. The helpPhrase is the same as you set it up "??".

Could you test and share the results?
Thanks.

**Comment by kbysiec** [comment] 2020-09-09 16:15
Nope, it doesn't need any internet at all. How many files approximately you may have?

**Comment by kbysiec** [comment] 2020-09-28 08:13
Closed because of inactivity.

**Closed by kbysiec** 2020-09-28 08:13 UTC
Labels: question
